name: Security Workflow

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  sca:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        requirements:
          [
            requirements/one-requirements.txt,
            requirements/two-requirements.txt,
            requirements/three-requirements.txt,
          ]
    steps:
      - uses: actions/checkout@master

      - name: Install Python Dependencies
        run: |
          pip install -r ${{ matrix.requirements }}
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: ''

      - name: Setup Snyk and run test
        run: |
          npm install snyk -g
          snyk auth ${{secrets.SNYK_TOKEN}}
          snyk test --package-manager=pip --file=${{ matrix.requirements }}
        continue-on-error: true

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --package-manager=pip --file=${{ matrix.requirements }}
